[project]
name = "llm-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
    "rdkit>=2026.3.1",
    "torch==2.11.0+xpu",
    "tqdm>=4.67.3",
    "triton-xpu==3.7.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-xpu" },
]
torchvision = [
    { index = "pytorch-xpu" },
]
triton-xpu = [
  { index = "pytorch-xpu" },
]

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
